<?php defined( 'ABSPATH' ) OR die( 'This script cannot be accessed directly.' );

return array(
	array(
		'name' => 'Fullwidth Accordion Sections',
		'content' => '[vc_row height="auto" width="full"][vc_column width="1/1"][vc_tta_accordion c_align="center"][vc_tta_section title="Targeted Branding" icon="fa-bullseye"][vc_row_inner][vc_column_inner width="1/3"][us_iconbox icon="fa-globe" color="light" iconpos="left" title="Set Goals" external="" style="circle" link=""]I am text block. Click edit button to change this text. Lorem ipsum dolor sit amet ut elit tellus.[/us_iconbox][/vc_column_inner][vc_column_inner width="1/3"][us_iconbox icon="fa-plane" color="light" iconpos="left" title="Reach" style="circle"]I am text block. Click edit button to change this text. Lorem ipsum dolor sit amet ut elit tellus.[/us_iconbox][/vc_column_inner][vc_column_inner width="1/3"][us_iconbox icon="fa-repeat" color="light" iconpos="left" title="Repeat" style="circle"]I am text block. Click edit button to change this text. Lorem ipsum dolor sit amet ut elit tellus.[/us_iconbox][/vc_column_inner][/vc_row_inner][/vc_tta_section][vc_tta_section title="Geolocating Features" icon="fa-map-marker"][vc_row_inner][vc_column_inner width="1/2"][vc_column_text]Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi non enim suscipit, dignissim diam at, laoreet eros. Aenean vitae orci nisi. Curabitur luctus ligula vel orci bibendum accumsan. Fusce ac tortor quis nisl posuere accumsan ut sit amet nisl. Pellentesque quis ultricies lacus, et lobortis libero. Quisque consectetur euismod egestas. Praesent hendrerit fringilla.

Donec id mattis velit. Vivamus viverra, erat tempus commodo sagittis, nibh arcu varius enim, sit amet congue eros magna dictum nibh. Praesent tristique lectus sed lorem scelerisque, vel vestibulum tortor varius. Vivamus vestibulum nisl mauris, nec bibendum eros vulputate vitae. Donec rutrum sem ut mi tempor suscipit id quam tristique auctor.[/vc_column_text][/vc_column_inner][vc_column_inner width="1/2"][vc_column_text]Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi non enim suscipit, dignissim diam at, laoreet eros. Aenean vitae orci nisi. Curabitur luctus ligula vel orci bibendum accumsan. Fusce ac tortor quis nisl posuere accumsan ut sit amet nisl. Pellentesque quis ultricies lacus, et lobortis libero. Quisque consectetur euismod egestas. Praesent hendrerit fringilla.

Donec id mattis velit. Vivamus viverra, erat tempus commodo sagittis, nibh arcu varius enim, sit amet congue eros magna dictum nibh. Praesent tristique lectus sed lorem scelerisque, vel vestibulum tortor varius. Vivamus vestibulum nisl mauris, nec bibendum eros vulputate vitae. Donec rutrum sem ut mi tempor suscipit id quam tristique auctor.[/vc_column_text][/vc_column_inner][/vc_row_inner][/vc_tta_section][vc_tta_section title="Marketing Strategy" icon="fa-diamond"][vc_row_inner][vc_column_inner width="1/3"][vc_column_text]I am text block. Click edit button to change this text. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.[/vc_column_text][/vc_column_inner][vc_column_inner width="1/3"][vc_column_text]I am text block. Click edit button to change this text. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.[/vc_column_text][/vc_column_inner][vc_column_inner width="1/3"][vc_column_text]I am text block. Click edit button to change this text. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.[/vc_column_text][/vc_column_inner][/vc_row_inner][/vc_tta_section][/vc_tta_accordion][/vc_column][/vc_row]',
	),
	array(
		'name' => '3 Boxes Features Columns',
		'content' => '[vc_row columns_type="boxes" height="auto" width="full"][vc_column width="1/3" css=".vc_custom_1426762592726{background-image: url(http://us-themes.com/wp-content/uploads/placeholders/us-placeholder-landscape.jpg?id=1) !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}" text_color="#ffffff"][vc_column_text]
<h3>Fully Featured &amp; Flexible</h3>
I am text block. Click edit button to change this text. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.[/vc_column_text][us_btn text="Tell me more" color="white" style="outlined" link="url:%23"][/vc_column][vc_column width="1/3" text_color="#ffffff" css=".vc_custom_1426688097558{background-image: url(http://us-themes.com/wp-content/uploads/placeholders/us-placeholder-landscape.jpg?id=1) !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}"][vc_column_text]
<h3>Modern Design &amp; Trendy Look</h3>
I am text block. Click edit button to change this text. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.[/vc_column_text][us_btn text="Tell me more" color="white" style="outlined" link="url:%23"][/vc_column][vc_column width="1/3" text_color="#ffffff" css=".vc_custom_1426688491496{background-image: url(http://us-themes.com/wp-content/uploads/placeholders/us-placeholder-landscape.jpg?id=1) !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}"][vc_column_text]
<h3>Wonderful Digital Things</h3>
I am text block. Click edit button to change this text. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.[/vc_column_text][us_btn text="Tell me more" color="white" style="outlined" link="url:%23"][/vc_column][/vc_row]',
	),
	array(
		'name' => 'Hero Section 1',
		'content' => '[vc_row height="huge" color_scheme="secondary" us_bg_image="66" us_bg_parallax="vertical"][vc_column el_class="align_center"][vc_custom_heading text="THINK LIKE A
<strong>CUSTOMER</strong>" font_container="tag:h2|font_size:60|text_align:center" use_theme_fonts="yes"][us_btn text="More Info" color="white"][us_btn text="Purchase"][/vc_column][/vc_row]',
	),
);